/**
 * NIVARAN — DisclaimerModal Component (v2)
 * Glassmorphism legal disclaimer with animated entrance and improved typography.
 */

import React from 'react';

function DisclaimerModal({ onAccept }) {
  return (
    <div className="modal-overlay-v2" id="disclaimer-modal">
      <div className="modal-content-v2">
        {/* Decorative gradient top bar */}
        <div className="modal-v2-gradient-bar" />

        <div className="modal-v2-inner">
          <span className="modal-v2-icon">⚖️</span>
          <h2 className="modal-v2-title">Important Legal Disclaimer</h2>

          <div className="modal-v2-body">
            <p className="modal-v2-intro">
              Before using NIVARAN's Rent-Right scanner, please acknowledge:
            </p>

            <div className="modal-v2-items">
              <div className="modal-v2-item">
                <span className="modal-v2-item-icon">📋</span>
                <p>This tool provides <strong>informational analysis only</strong>, not legal advice.</p>
              </div>
              <div className="modal-v2-item">
                <span className="modal-v2-item-icon">🤖</span>
                <p>Results are generated by <strong>AI and rule-based systems</strong>, and may contain inaccuracies.</p>
              </div>
              <div className="modal-v2-item">
                <span className="modal-v2-item-icon">👨‍⚖️</span>
                <p>Always consult a qualified <strong>legal professional</strong> before making legal decisions.</p>
              </div>
              <div className="modal-v2-item">
                <span className="modal-v2-item-icon">🔒</span>
                <p>Documents are processed <strong>offline and in-memory</strong> — never stored or shared.</p>
              </div>
              <div className="modal-v2-item">
                <span className="modal-v2-item-icon">📜</span>
                <p>Analysis is based on the <strong>Model Tenancy Act, 2021</strong> and may not cover all jurisdictions.</p>
              </div>
            </div>
          </div>

          <div className="modal-v2-actions">
            <button
              className="btn btn-primary btn-large modal-v2-accept-btn"
              onClick={onAccept}
              id="disclaimer-accept-btn"
            >
              I Understand — Continue to Rent-Right
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DisclaimerModal;
