/**
 * NIVARAN — DisclaimerModal Component
 * Mandatory legal disclaimer shown before any analysis begins.
 * Uses localStorage to remember acceptance per session.
 */

import React from 'react';

function DisclaimerModal({ onAccept }) {
  return (
    <div className="modal-overlay" id="disclaimer-modal">
      <div className="modal-content">
        <span className="modal-icon">⚖️</span>
        <h2 className="modal-title">Important Legal Disclaimer</h2>
        <div className="modal-body">
          <p style={{ marginBottom: '16px' }}>
            Before using NIVARAN, please understand and acknowledge:
          </p>
          <ul>
            <li>
              This tool provides <strong>informational analysis only</strong>, not legal advice.
            </li>
            <li>
              Results are generated by AI and rule-based systems, and may contain inaccuracies.
            </li>
            <li>
              Always consult a qualified <strong>legal professional</strong> before making legal decisions.
            </li>
            <li>
              Your documents are processed <strong>in-memory only</strong> and are never stored or shared.
            </li>
            <li>
              Risk scores and flagged clauses are based on the <strong>Model Tenancy Act, 2021</strong> and may not cover all jurisdictions.
            </li>
          </ul>
        </div>
        <div className="modal-actions">
          <button
            className="btn btn-primary btn-large"
            onClick={onAccept}
            id="disclaimer-accept-btn"
          >
            I Understand — Continue
          </button>
        </div>
      </div>
    </div>
  );
}

export default DisclaimerModal;
